// This file is autogenerated by "./scripts/generate-icon-types.js". Do not edit it manually.

export enum IconName {
  Dots = "dots",
  Edit = "edit",
  Delete = "delete",
  DeleteDone = "delete-done",
  Close = "close",
  Settings = "settings",
  Drag = "drag",
  Pin = "pin",
  Unpin = "unpin"
}
